# A/B Testing Framework - Experiment Configuration Template
# This file defines the structure for setting up new experiments

experiment:
  name: "Example Experiment"
  description: "Testing feature X vs feature Y"
  status: "draft" # draft, running, paused, completed
  
  # Experiment timeline
  schedule:
    start_date: "2025-02-01"
    end_date: null # null for open-ended
    duration_days: 14
  
  # Hypothesis and goals
  hypothesis: "Changing X will improve Y by Z%"
  primary_metric: "conversion_rate"
  secondary_metrics:
    - "revenue_per_user"
    - "engagement_rate"
  
  # Traffic configuration
  traffic:
    allocation_percentage: 100 # % of total traffic
    min_sample_size: 10000
    max_sample_size: 50000
  
  # Variant definitions
  variants:
    - id: "control"
      name: "Control"
      description: "Current implementation"
      traffic_percentage: 50
      is_control: true
      
    - id: "treatment_a"
      name: "Treatment A"
      description: "New implementation"
      traffic_percentage: 50
      is_control: false
  
  # Statistical parameters
  statistics:
    confidence_level: 0.95
    statistical_power: 0.80
    minimum_detectable_effect: 0.05
    test_type: "two_tailed" # two_tailed, one_tailed
  
  # Guardrail metrics (safety checks)
  guardrails:
    - metric: "error_rate"
      threshold: 0.01
      direction: "decrease"
    - metric: "page_load_time"
      threshold: 3000
      direction: "increase"
  
  # Metadata
  metadata:
    owner: "product_team"
    tags: ["conversion", "ui_test"]
    priority: "high"
